DROP FUNCTION IF EXISTS create_role;
DROP FUNCTION IF EXISTS get_role_by_id;
DROP FUNCTION IF EXISTS get_roles;
DROP FUNCTION IF EXISTS update_role;
DROP FUNCTION IF EXISTS delete_role;

DROP TABLE IF EXISTS roles;

DROP TYPE IF EXISTS role_type;