DROP FUNCTION IF EXISTS create_user;
DROP FUNCTION IF EXISTS get_user_by_id;
DROP FUNCTION IF EXISTS get_users;
DROP FUNCTION IF EXISTS update_user;
DROP FUNCTION IF EXISTS delete_user;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS user_type;